### PR TITLE
ARM templates specific to secure Reverse Proxy

### PR DESCRIPTION
**Pull request by kavyako**
This PR includes:
1. ARM templates to enable and configure Reverse Proxy with new certificate.
2. ARM template to rollover reverse proxy certificate with a second certificate.
In both the examples here, the Reverse Proxy certificate is different from the cluster certificate.

### CODE REVIEW

**Comment by olandese** [comment]
@ChackDan is it possible to create a SF with a reverse Proxy with one template instead of using multiple templates ?

**Comment by kavyako** [comment]
Yes, refer to the [5-VM-1-NodeTypes-SecureRP_Step3.JSON ](https://github.com/ChackDan/Service-Fabric/blob/master/ARM%20Templates/ReverseProxySecureSample/5-VM-1-NodeTypes-SecureRP_Step3.json) in this repo.
You can deploy a cluster with this template to enable secure reverse proxy. 

2 step upgrades are required while adding a new reverse proxy certificate to an existing cluster or when updating the reverse proxy certificate.

**Comment by olandese** [comment]
Thank you @kavyako for the quick reply.
To generate the reverse proxy certificate (self signed) can I use the same steps as described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-arm (as described in the "Creating a self-signed certificate and uploading it to the key vault section") ?

**Comment by ChackDan** [comment]
you can use the same steps to generate and upload the cert to key vault.

**Pull request merged**
